name: Kitchenapp
version: 1.0.15+16

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  shared_preferences: ^0.5.8
  async_loader: ^0.1.2
  audioplayers: ^0.13.0
  onesignal_flutter: ^2.6.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl:

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/cover.png
    - lib/assets/images/sass.png
    - lib/assets/images/logo.png
    - lib/assets/logos/logo.png
    - lib/assets/logos/logo-light.png
    - lib/assets/i18n/en.json
    - lib/assets/i18n/fr.json
    - lib/assets/i18n/ar.json
    - lib/assets/i18n/zh.json
    - lib/assets/splash.png
