name: Kitchenapp
version: 1.0.19+20

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.0+4
  shared_preferences: ^0.5.7
  async_loader: ^0.1.2
  onesignal_flutter: ^2.4.0
  audioplayers: ^0.16.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl:

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/cover.png
    - lib/assets/images/sass.png
    - lib/assets/images/logo.png
    - lib/assets/logos/logo.png
    - lib/assets/i18n/en.json
    - lib/assets/i18n/es.json
    - lib/assets/splash.png
